import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import { ThemeProvider } from '@/components/ui/providers/theme-provider'
const font = Open_Sans({ subsets: ['latin'] })
import { cn } from '@/lib/utils'
export const metadata: Metadata = {
  title: 'Discorb',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning>
      <body className={cn(font.className,
        "bg-white dark:bg-[#1f2228]")}>
        <ThemeProvider 
        attribute='class'
        defaultTheme='dark'
        enableSystem={false}
        storageKey='discord-theme'>
        {children}
        </ThemeProvider>
        </body>
    </html>
    </ClerkProvider>
  )
}
